---
- name: Create process.d conf directory
  file:
    path: "{{ dd_confd_dir }}/process.d"
    state: directory
    owner: dd-agent
    group: dd-agent
    mode: '0750'

- name: Deploy Mailcow process check config
  template:
    src: process_mailcow.yaml.j2
    dest: "{{ dd_confd_dir }}/process.d/conf.yaml"
    owner: dd-agent
    group: dd-agent
    mode: '0640'
  notify: restart datadog-agent
  when: has_mailcow | bool

- name: Deploy Postal process check config
  template:
    src: process_postal.yaml.j2
    dest: "{{ dd_confd_dir }}/process.d/conf.yaml"
    owner: dd-agent
    group: dd-agent
    mode: '0640'
  notify: restart datadog-agent
  when: has_postal | bool and not (has_mailcow | bool)
