- name: Create redisdb.d conf directory
  file:
    path: "{{ dd_confd_dir }}/redisdb.d"
    state: directory
    owner: dd-agent
    group: dd-agent
    mode: '0750'

- name: Remove Redis Autodiscovery config (conflicts with our static config)
  file:
    path: "{{ dd_confd_dir }}/redisdb.d/auto_conf.yaml"
    state: absent
  notify: restart datadog-agent

- name: Deploy Redis integration config
  template:
    src: redis_conf.yaml.j2
    dest: "{{ dd_confd_dir }}/redisdb.d/conf.yaml"
    owner: dd-agent
    group: dd-agent
    mode: '0640'
  notify: restart datadog-agent