[mail_servers]
test-mailcow  ansible_host=66.206.9.5
inbound-694-01a ansible_host=72.244.205.176
; inbound-419-02b  ansible_host=10.0.1.11
; globalrelay1     ansible_host=10.0.2.10

[inbound_servers]
inbound-694-01a
inbound-419-02b

; [outbound_servers]
; globalrelay1

[mail_servers:vars]
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/id_ed25519

[proxmox_nodes]
node-ca-002-0001 ansible_host=54.38.113.24
node-ca-01-0001 ansible_host=148.113.170.24
node-hi-01-0003 ansible_host=66.206.9.2
node-ca-01-0003 ansible_host=148.113.161.177
node-hi-10-0001 ansible_host=23.227.207.166
node-hi-20-0001 ansible_host=23.227.207.146
node-hi-50-0001 ansible_host=107.155.100.82
; pve01  ansible_host=10.0.0.10
; pve02  ansible_host=10.0.0.11

[proxmox_nodes:vars]
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/id_ed25519
