[mail_servers]
test-mailcow  ansible_host=66.206.9.5
inbound-694-01a ansible_host=72.244.205.176
; inbound-419-02b  ansible_host=10.0.1.11
; globalrelay1     ansible_host=10.0.2.10
outbound-834-05a ansible_host=5.135.110.107
outbound-834-04a ansible_host=5.135.110.106
outbound-834-06a ansible_host=5.135.110.108
outbound-834-07a ansible_host=5.135.110.109
outbound-1003-01 ansible_host=5.135.110.110
outbound-1006-01 ansible_host=5.135.110.170
; outbound-928-01 ansible_host=5.135.110.171 issue disk mount.
; outbound-928-01a ansible_host=5.135.110.172 issue disk mount.
outbound-929-01 ansible_host=5.135.110.173
oubound-419-01a ansible_host=5.135.110.174
oubound-419-01b ansible_host=5.135.26.138
outbound-925-01 ansible_host=5.135.26.139
outbound-934-01 ansible_host=5.135.26.140
outbound-933-01 ansible_host=5.135.26.141
outbound-936-01 ansible_host=5.135.26.142

[outbound_servers]
outbound-834-05a
outbound-834-04a
outbound-834-06a
outbound-834-07a
outbound-1003-01
outbound-1006-01
; outbound-928-01
; outbound-928-01a
outbound-929-01
oubound-419-01a
oubound-419-01b
outbound-925-01 
outbound-934-01
outbound-933-01
outbound-936-01 

[outbound_servers:vars]
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/mo.pem


[inbound_servers]
inbound-694-01a
inbound-419-02b

; [outbound_servers]
; globalrelay1

; [mail_servers:vars]
; ansible_user=root
; ansible_ssh_private_key_file=~/.ssh/id_ed25519

[inbound_servers:vars]
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/id_ed25519

[proxmox_nodes]
node-ca-002-0001 ansible_host=54.38.113.24
node-ca-01-0001 ansible_host=148.113.170.24
node-hi-01-0003 ansible_host=66.206.9.2
node-ca-01-0003 ansible_host=148.113.161.177
node-hi-10-0001 ansible_host=23.227.207.166
node-hi-20-0001 ansible_host=23.227.207.146
node-hi-50-0001 ansible_host=107.155.100.82
; pve01  ansible_host=10.0.0.10
; pve02  ansible_host=10.0.0.11

[proxmox_nodes:vars]
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/id_ed25519

[jumpservers]
jumpserver ansible_host=127.0.0.1

[jumpservers:vars]
ansible_user=infra-admin
ansible_ssh_private_key_file=~/.ssh/id_ed25519
