[mail_servers]
test-mailcow  ansible_host=15.204.216.182
; inbound-419-02b  ansible_host=10.0.1.11
; globalrelay1     ansible_host=10.0.2.10

; [inbound_servers]
; inbound-419-01b
; inbound-419-02b

; [outbound_servers]
; globalrelay1

[mail_servers:vars]
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/id_ed25519
