

[outbound_servers:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/mo.pem

[postal_outbound]
mail.outboundhoustonrocket.com ansible_host=15.204.142.178 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/old-mailin-out.pem




[outbound_servers]
outbound-929-01  ansible_host=5.135.110.173
oubound-419-01a  ansible_host=5.135.110.174
oubound-419-01b  ansible_host=5.135.26.138
outbound-925-01  ansible_host=5.135.26.139
outbound-934-01  ansible_host=5.135.26.140
outbound-933-01  ansible_host=5.135.26.141
outbound-936-01  ansible_host=5.135.26.142
; outbound-834-05a ansible_host=5.135.110.107  ; issue disk mount
; outbound-834-04a ansible_host=5.135.110.106  ; issue disk mount
; outbound-834-06a ansible_host=5.135.110.108  ; issue disk mount
; outbound-834-07a ansible_host=5.135.110.109  ; issue disk mount
; outbound-1003-01 ansible_host=5.135.110.110  ; issue disk mount
; outbound-1006-01 ansible_host=5.135.110.170  ; issue disk mount

[mailin_outbound:children]
postal_outbound
