---
galaxy_info:
  role_name: mailcow_expunge
  author: mailin
  description: Expunge messages older than 2 weeks from all dovecot mailboxes
  min_ansible_version: "2.12"
  platforms:
    - name: Debian
      versions: [bullseye, bookworm]
    - name: Ubuntu
      versions: ["20.04", "22.04", "24.04"]
dependencies: []
