---
- name: restart datadog-agent
  service:
    name: datadog-agent
    state: restarted

- name: restart datadog-agent-sysprobe
  service:
    name: datadog-agent-sysprobe
    state: restarted
  failed_when: false
